### ISSUE TITLE
Add..

### ISSUE THREAD

**Issue by dkhamsing** [jeffreyjackson/mac-apps#14]
https://github.com/scrod/nv

**Comment by jeffreyjackson** [comment]
seems old - what do you think?  i doubt it would build in its current state.

**Comment by dkhamsing** [comment]
good point, check out this fork https://github.com/ttscoff/nv

**Comment by dkhamsing** [comment]
https://github.com/salomvary/soundcleod

**Comment by jeffreyjackson** [comment]
thanks man!
