### ISSUE TITLE
https://github.com/bayandin/awesome-awesomeness ?

### ISSUE THREAD

**Issue by Trevoke** [jeffreyjackson/mac-apps#4]
Are you aware of this? https://github.com/bayandin/awesome-awesomeness

**Comment by jeffreyjackson** [comment]
Yes I am, we would be relying on 1 person to maintain that going forward.  If we had it under an org, we could get more traction and have multiple users manage.

**Comment by Trevoke** [comment]
Have you considered asking whether that existing repository could just be moved to an organization, as a starting point? 

It seems like a saner starting point than reinventing the wheel, doesn't it?

**Comment by jeffreyjackson** [comment]
Yes, I have asked and am looking to transfer the repo
