### ISSUE TITLE
Add ScreenToLayers

### ISSUE THREAD

**Issue by jeremyvizzini** [jeffreyjackson/mac-apps#41]
Hi,

I think ScreenToLayers could be add to the list.

ScreenToLayers : open-source mac app to save your screen as a layered psd.
[http://www.screentolayersapp.com](http://www.screentolayersapp.com)
[http://github.com/jeremyvizzini/ScreenToLayers](http://github.com/jeremyvizzini/ScreenToLayers)

**Comment by jeffreyjackson** [comment]
@jeremyvizzini feel free to open a PR
